<div class="banner container">
    <img src="{{ asset('img/dc-logo.png') }}" alt="">
    <nav>
        <ul>
            <li>
                Characters
            </li>
            <li>
                Comics
            </li>
            <li>
                Movies
            </li>
            <li>
                Tv
            </li>
            <li>
                Games
            </li>
            <li>
                Collectibles
            </li>
            <li>
                Videos
            </li>
            <li>
                Fans
            </li>
            <li>
                News
            </li>
            <li>
                Shop
            </li>
        </ul>
    </nav>
</div>
